FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:latest
USER 185
WORKDIR /deployments
COPY --chown=185:root target/quarkus-app/lib/ /deployments/lib/
COPY --chown=185:root target/quarkus-app/*.jar /deployments/
COPY --chown=185:root target/quarkus-app/app/ /deployments/app/
COPY --chown=185:root target/quarkus-app/quarkus/ /deployments/quarkus/
ENV JAVA_OPTS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
EXPOSE 8087
ENTRYPOINT [ "java", "-jar", "/deployments/quarkus-run.jar" ]