server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/*log

  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containers
          __path__: /var/lib/docker/containers/*/*.log

  - job_name: microservice
    static_configs:
      - targets:
          - localhost
        labels:
          job: microservice
          app: microservice-template
          __path__: /var/log/microservice/*.log

  - job_name: apps
    pipeline_stages:
      - json:
          expressions:
            level: level
            timestamp: timestamp
            message: message
            logger: logger
      - labels:
          level:
          logger:
    static_configs:
      - targets:
          - localhost
        labels:
          job: apps
          __path__: /var/log/apps/*.log